# Generated by Django 5.0.3 on 2024-03-22 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="group",
            field=models.ForeignKey(
                default="6f0204f0-63a7-4ad6-ac5e-c3314d24f8be",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.group",
            ),
            preserve_default=False,
        ),
    ]
