# Generated by Django 5.1.2 on 2024-12-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="color",
            new_name="emoji",
        ),
    ]
